### PR TITLE
[optimizer] add missing runtime dependencies

### PR DESCRIPTION
**Pull request by sebastianbenz**

### CODE REVIEW

**Comment by sebastianbenz** [comment]
CLI has been signed if #798

**Comment by merceyz** [comment]
Seems you removed `cross-fetch` which is also needed

**Comment by sebastianbenz** [comment]
@merceyz cross-fetch is a transitive dependency of toolbox-core

**Comment by merceyz** [comment]
That makes us rely on hoisting which is a really, really bad idea, if you want to require it from toolbox-core you should use createRequire/have toolbox-core export it.

**Comment by sebastianbenz** [comment]
Thanks for the explanation. Will add it.

**Comment by merceyz** [comment]
Awesome, thank you. Also, the same issue is present for toolbox-cli, it tries to use toolbox-core without declaring it

**Pull request merged**
