### PR TITLE
Skip fonts with a data: URL source from fontPreloading check

### LINKED ISSUE #1185: fontPreloading check erroneously advises to preload a font which is a data: URL
When running Pixi on https://www.cu-camper.com/en/ I saw unexpected advice for **Preload critical fonts**:

> image

Namely, the font is present on the page as a `data:` URL and thus it is irrelevant for preloading.

Interestingly, the font in question is coming from a page inside of an `amp-iframe`: https://cumagazin.cu-camper.com/en/magazine/map/?center=41.4825133,2.4863493&zoom=2&lightbox=1&language=en

I believe the logic here should be changed:

https://github.com/ampproject/amp-toolbox/blob/42ff00a68c2fdbe2a0cf3684ddeefc482c8b07f8/packages/page-experience/lib/checks/fontPreloading.js#L25-L28

Namely to something like:

```js
if (!fontface || !fontface.mainSrc || fontface.mainSrc.startsWith('data:')) { 
```

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #1185

### CODE REVIEW

**Review by sebastianbenz — CHANGES_REQUESTED** [review]
Can you please add a test here: https://github.com/ampproject/amp-toolbox/tree/main/packages/page-experience/test-data/checks/fontPreloading

You can then run `npm run test:snapshot` to generate a snapshot.

**Comment by westonruter** [comment]
I added a test in e9159fb.

> You can then run `npm run test:snapshot` to generate a snapshot.

Actually `npm run test:optimizer:snapshot`, right? In any case, it's not seeming to work for me. Even on `main` it's failing with a with a bunch of errors like:

image

I did do `npm install`. I'm on Node v14.16.0 (LTS).

**Comment by sebastianbenz** [comment]
You need to run it inside the page-experience directory. Sorry for not mentioning that.

**Comment by westonruter** [comment]
OK, I'm now in `packages/page-experience` and I ran `npm install`. However:

```
$ npm run test:snapshot

> @ampproject/toolbox-page-experience@2.8.0-canary.14 test:snapshot /Users/westonruter/repos/amp-toolbox/packages/page-experience
> PAGE_EXPERIENCE_SNAPSHOT=true jest

sh: jest: command not found
```

Shouldn't `jest` be added as a dependency?

**Comment by westonruter** [comment]
OK, I'm now in `packages/page-experience` and I ran `npm install`. However:

```
$ npm run test:snapshot

> @ampproject/toolbox-page-experience@2.8.0-canary.14 test:snapshot …/amp-toolbox/packages/page-experience
> PAGE_EXPERIENCE_SNAPSHOT=true jest

sh: jest: command not found
```

Shouldn't `jest` be added as a dependency?

**Review by sebastianbenz — APPROVED** [review]

**Pull request merged**
