### PR TITLE
Apply `slot="i-amphtml-svc"` to sizer elements.

### PR DESCRIPTION
**Pull request by caroqliu**
Partial for ampproject/amphtml/issues/35485. Do not submit until ampproject/amphtml/pull/35679 is merged and deployed. Related: cl/389672066

### CODE REVIEW

**Review by westonruter — APPROVED** [review]
LGTM, but we'll need to re-check once validation spec changes have been deployed.

**Comment by caroqliu** [comment]
ping @sebastianbenz please review, feel free to merge if acceptable

**Review by schlessera — APPROVED** [review]

**Comment by schlessera** [comment]
@caroqliu It looks like something went wrong here, and you've merged into a branch, closing this PR. This is not merged into the `main` branch and needs reopening/recreating.

**Comment by westonruter** [comment]
I've opened the PR to do so: https://github.com/ampproject/amp-toolbox/pull/1261

**Comment by caroqliu** [comment]
Thanks both!

**Pull request merged**
