### PR TITLE
Proxy support for amp-optimizer

### PR DESCRIPTION
**Pull request by todoa2c**
Proxy support using node-fetch-with-proxy instead of node-fetch.
If you need to use proxy, just set the environment variable `https_proxy`.

Thanks.

### CODE REVIEW

**Comment by todoa2c** [comment]
@googlebot I signed it!

**Comment by sebastianbenz** [comment]
Thanks for creating this! One suggestion: as the code for integrating this is trivial, would you mind implementing this directly instead of adding an additional dependency?

**Comment by sebastianbenz** [comment]
Sorry for not being more clear. Integrating `https://www.npmjs.com/package/http-proxy-agent` is fine as it seems to be the "standard" node way of integrating of proxy. What I'd like to avoid is integrating `node-fetch-with-proxy` as it's a super thin wrapper with only a few LOC and super low usage.

**Comment by todoa2c** [comment]
@sebastianbenz Sorry for late reaction.
This time `https-proxy-agent` matches so I added and fixed code.

**Comment by todoa2c** [comment]
@sebastianbenz I checked `cross-fetch` library but it doesn't support agent like `node-fetch`.

Should I replace cross-fetch to node-fetch? or any ideas?

**Comment by sebastianbenz** [comment]
Hm - that's annoying. I think it's fine to replace cross-fetch in that case and we don't release a browser bundle yet which would benefit from cross fetch.

**Comment by todoa2c** [comment]
@sebastianbenz Ok, so let's try replacing "cross-fetch" with "node-fetch" once in a separate branch.
Is it possible to merge this pull request? I'm using next.js now, but I'm having trouble with next.js because it relies on amp-toolbox and I'm having to wait a huge amount of time for postinstall in a proxy environment.

**Pull request merged**
